### ISSUE TITLE
Gintama - Yorozuya Chuubu support

### ISSUE THREAD

**Issue by Andree12** [Nisto/lzsd#1]
I discovered that many files from Gintama - Yorozuya Chuubu can work with lzsd_of, but some do not work but can you (or someone) at least improve lzsd_of so that it works with some files inside this zip file below?
[compressed o_title files.zip](https://github.com/user-attachments/files/17122000/compressed.o_title.files.zip)

**Comment by Nisto** [comment]
@Andree12 You mentioned it works with some files. I tested decompressing all of the files in your archive with lzsd_of, but none of them decompressed properly? Can you post some of the files that it worked on, assuming they are not already in the archive?

**Comment by Nisto** [comment]
@Andree12 Have a look at lzsd_gyctd just posted to the repo / release page.
